//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nanolite_agent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebugMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebugMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nanolite_agent.Properties.DebugMessages", typeof(DebugMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectorIP is not set in the config file.
        /// </summary>
        public static string ConfigCollectorIPErrMessage {
            get {
                return ResourceManager.GetString("ConfigCollectorIPErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollectorPort is not set in the config file.
        /// </summary>
        public static string ConfigCollectorPortErrMessage {
            get {
                return ResourceManager.GetString("ConfigCollectorPortErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporter is not set in the config file.
        /// </summary>
        public static string ConfigExporterErrMessage {
            get {
                return ResourceManager.GetString("ConfigExporterErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deserializing config file.
        /// </summary>
        public static string ConfigFileDeserializeErrMessage {
            get {
                return ResourceManager.GetString("ConfigFileDeserializeErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file is empty.
        /// </summary>
        public static string ConfigFileErrMessage {
            get {
                return ResourceManager.GetString("ConfigFileErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while read config file.
        /// </summary>
        public static string ConfigFileReadErrMessage {
            get {
                return ResourceManager.GetString("ConfigFileReadErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config path cannot be null or empty.
        /// </summary>
        public static string ConfigPathErrMessage {
            get {
                return ResourceManager.GetString("ConfigPathErrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program terminated. Press any button to exit..
        /// </summary>
        public static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        public static string PrivilegeMessage {
            get {
                return ResourceManager.GetString("PrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null or empty.
        /// </summary>
        public static string SystemActivityNullException {
            get {
                return ResourceManager.GetString("SystemActivityNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace event data is not acceptable.
        /// </summary>
        public static string TracepointAcceptErrMessage {
            get {
                return ResourceManager.GetString("TracepointAcceptErrMessage", resourceCulture);
            }
        }
    }
}
